### ISSUE TITLE
where we should store the decimal part?

### ISSUE THREAD

**Issue by bhavyaBeliever** [prathampt/calc#4]
hello everyone, i had read the toNumber function and the issue i faced is we haven't handled the decimal part.
please decide about it.
Also please specify that why we have use doubly linked list instead we store the numbers in reverse order of singly linked list.

**Comment by prathampt** [comment]
The toNumber function has been modified for considering the digits after the decimal point. The remaining code will be soon changed to adapt these updates in the base data structure of the Number... Soon the issue will be sorted...

Thanks for raising the issue and making me aware of the remaining work...

**Comment by prathampt** [comment]
Issue resolved, implemented the code for decimal part. The code now supports the decimal part for all three functions add, subtract and multiply written so far...
